.lator_gui_rows <- function(values) {
  if (!length(values)) return(list())
  if (is.data.frame(values)) {
    return(unname(lapply(seq_len(nrow(values)), function(index) as.list(values[index, , drop = FALSE]))))
  }
  unname(lapply(values, function(value) as.list(value)))
}

.lator_gui_payload <- function(workspace, patient_id = NULL, models = list(),
                               endpoints = list(), selected_model = NULL,
                               selected_endpoint = NULL, regimen = NULL,
                               selected_candidate = NULL, prediction = NULL,
                               status = list(level = "info", text = "Workbench ready"),
                               icon = NULL) {
  patients <- lator_patient_list(workspace)
  patient <- if (!is.null(patient_id) && patient_id %in% patients$patient_id) {
    lator_patient_get(workspace, patient_id)
  } else NULL
  events <- if (is.null(patient)) list() else lapply(.lator_active_events(patient), function(event) list(
    id = event$event_id, type = event$type, time = event$time, name = event$name,
    value = if (length(event$value) == 1L && !is.na(event$value)) event$value else NULL,
    unit = event$unit, source = event$source, missing = event$missing_reason,
    occasion = if (is.finite(event$occasion)) event$occasion else NULL
  ))
  assessments <- if (is.null(patient)) list() else lapply(patient$assessments, function(item) list(
    id = item$assessment_id, at = item$created_at, cutoff = item$cutoff, mode = item$mode,
    convergence = item$convergence, eta = .lator_gui_rows(item$eta_trajectory),
    target = item$endpoint_evaluation, diagnostics = item$diagnostics,
    warnings = as.character(item$warnings %||% character())
  ))
  current <- if (length(assessments)) utils::tail(assessments, 1L)[[1L]] else NULL
  model_rows <- lapply(names(models), function(id) list(
    id = id, name = attr(models[[id]], "name", exact = TRUE) %||% id,
    advan = models[[id]]$ADVAN, trans = models[[id]]$TRANS,
    etas = models[[id]]$n_eta, source = if (length(attr(models[[id]], "library_provenance", exact = TRUE))) "LibeRary" else "local"
  ))
  endpoint_rows <- lapply(names(endpoints), function(id) list(
    id = id, name = endpoints[[id]]$name, drug = endpoints[[id]]$drug,
    kind = endpoints[[id]]$kind, status = endpoints[[id]]$status,
    lower = endpoints[[id]]$rules$lower %||% NULL,
    upper = endpoints[[id]]$rules$upper %||% NULL,
    unit = endpoints[[id]]$unit, source = endpoints[[id]]$source
  ))
  list(
    patients = .lator_gui_rows(patients), patient = if (is.null(patient)) NULL else list(
      id = patient$patient_id, label = patient$label, study = patient$study_id,
      revision = patient$revision, eventCount = length(patient$events), status = patient$status
    ),
    events = events, assessments = assessments, current = current,
    models = model_rows, endpoints = endpoint_rows,
    selectedModel = selected_model, selectedEndpoint = selected_endpoint,
    regimen = if (is.null(regimen)) NULL else list(
      summary = .lator_gui_rows(regimen$summary), selectedCandidate = selected_candidate
    ),
    prediction = if (is.null(prediction)) NULL else list(
      id = prediction$prediction_id, candidateId = prediction$candidate_id,
      assessmentId = prediction$assessment_id,
      regimen = as.list(prediction$regimen[1L, , drop = FALSE]),
      forecast = .lator_gui_rows(prediction$forecast),
      target = prediction$target,
      evaluation = prediction$evaluation,
      probabilities = as.numeric(prediction$interval_probabilities),
      generatedAt = prediction$generated_at
    ),
    icon = icon,
    status = status, packageVersion = tryCatch(
      as.character(utils::packageVersion("LibeRator")), error = function(error) "0.1.0"
    ),
    researchOnly = TRUE
  )
}

#' LibeRator React workbench widget
#' @param payload Workbench payload generated by the Shiny application.
#' @param input_id Shiny event prefix.
#' @param width,height Widget dimensions.
#' @param elementId Optional widget element id.
#' @export
liberator_workbench <- function(payload, input_id = "liberator_workbench",
                                width = NULL, height = "100vh", elementId = NULL) {
  content <- reactR::component("LibeRatorWorkbench", c(payload, list(inputId = input_id)))
  htmlwidgets::createWidget(
    name = "liberatorWorkbench", reactR::reactMarkup(content), width = width,
    height = height, package = "LibeRator", elementId = elementId
  )
}

#' @noRd
widget_html.liberatorWorkbench <- function(id, style, class, ...) {
  htmltools::attachDependencies(
    htmltools::tags$div(id = id, class = class, style = style),
    list(reactR::html_dependency_corejs(), reactR::html_dependency_react(), reactR::html_dependency_reacttools())
  )
}

#' Shiny output for the LibeRator workbench
#' @param outputId Output id.
#' @param width,height CSS dimensions.
#' @export
liberatorWorkbenchOutput <- function(outputId, width = "100%", height = "100vh") {
  htmlwidgets::shinyWidgetOutput(outputId, "liberatorWorkbench", width, height, package = "LibeRator")
}

#' Render a LibeRator workbench
#' @param expr Widget expression.
#' @param env Evaluation environment.
#' @param quoted Whether expression is quoted.
#' @export
renderLiberatorWorkbench <- function(expr, env = parent.frame(), quoted = FALSE) {
  if (!quoted) expr <- substitute(expr)
  htmlwidgets::shinyRenderWidget(expr, liberatorWorkbenchOutput, env, quoted = TRUE)
}
